language: python
sudo: false
python:
  - "3.5"
  - "3.6"
install:
  - pip install tox-travis
  - pip install sphinx sphinx_rtd_theme
script:
  - tox
  - python setup.py build_sphinx
after_success:
  - codecov
